#!/usr/bin/env python3
"""Generate responsive WebP derivatives from the image originals.

The originals do not live in this repository — they were 90 MB of camera files
that the site never served, since every image is delivered from the derivatives
instead. They sit in a sibling directory:

    pavel6625.github.io-originals/img/

Originals are never modified. Derivatives land in assets/img/derived/ (which is
committed) and a manifest is written to _data/images.yml so templates can emit
srcset, sizes and real intrinsic width/height — the last of which is what
actually stops layout shift.

    python tools/build_images.py                 # default sibling directory
    python tools/build_images.py --src PATH      # somewhere else
"""

import argparse
import hashlib
import pathlib
import re
import sys

from PIL import Image, ImageOps

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT.parent / "pavel6625.github.io-originals" / "img"
OUT = ROOT / "assets" / "img" / "derived"
MANIFEST = ROOT / "_data" / "images.yml"

WIDTHS = [480, 960, 1600]
QUALITY = 82
EXTS = {".jpg", ".jpeg", ".png"}


CYRILLIC = {
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ё": "e",
    "ж": "zh", "з": "z", "и": "i", "й": "y", "к": "k", "л": "l", "м": "m",
    "н": "n", "о": "o", "п": "p", "р": "r", "с": "s", "т": "t", "у": "u",
    "ф": "f", "х": "kh", "ц": "ts", "ч": "ch", "ш": "sh", "щ": "shch",
    "ъ": "", "ы": "y", "ь": "", "э": "e", "ю": "yu", "я": "ya",
}


def slug_for(path: pathlib.Path) -> str:
    """ASCII-safe, collision-free stem.

    Sources include spaces and Cyrillic; without transliteration a name like
    "Игры в бисер 05.jpg" collapsed to just "05", which is unhelpful to anyone
    reading the directory later.
    """
    lowered = path.stem.lower()
    stem = "".join(CYRILLIC.get(ch, ch) for ch in lowered)
    stem = re.sub(r"[^a-z0-9]+", "-", stem).strip("-")
    stem = stem[:48] or "img"
    digest = hashlib.md5(path.name.encode("utf-8")).hexdigest()[:8]
    return f"{stem}-{digest}"


def yaml_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src", type=pathlib.Path, default=DEFAULT_SRC,
        help=f"directory of original images (default: {DEFAULT_SRC})",
    )
    args = parser.parse_args()
    src = args.src

    if not src.is_dir():
        print(f"originals not found: {src}", file=sys.stderr)
        print("Pass --src if your archive lives elsewhere.", file=sys.stderr)
        return 1
    OUT.mkdir(parents=True, exist_ok=True)

    entries = []
    made = skipped = 0
    bytes_in = bytes_out = 0

    for path in sorted(src.iterdir()):
        if not path.is_file() or path.suffix.lower() not in EXTS:
            continue

        try:
            with Image.open(path) as im:
                im = ImageOps.exif_transpose(im)  # honour phone rotation
                if im.mode not in ("RGB", "RGBA"):
                    im = im.convert("RGBA" if "A" in im.getbands() else "RGB")
                width, height = im.size
                slug = slug_for(path)
                bytes_in += path.stat().st_size

                variants = []
                for w in WIDTHS:
                    if w > width:
                        continue
                    dest = OUT / f"{slug}-{w}.webp"
                    if not dest.exists():
                        h = round(height * w / width)
                        im.resize((w, h), Image.LANCZOS).save(
                            dest, "WEBP", quality=QUALITY, method=6
                        )
                        made += 1
                    else:
                        skipped += 1
                    bytes_out += dest.stat().st_size
                    variants.append(w)

                # Originals narrower than the smallest step still need an entry.
                if not variants:
                    dest = OUT / f"{slug}-{width}.webp"
                    if not dest.exists():
                        im.save(dest, "WEBP", quality=QUALITY, method=6)
                        made += 1
                    else:
                        skipped += 1
                    bytes_out += dest.stat().st_size
                    variants.append(width)

                entries.append(
                    {
                        "key": f"/assets/img/{path.name}",
                        "slug": slug,
                        "width": width,
                        "height": height,
                        "variants": variants,
                    }
                )
        except Exception as exc:  # noqa: BLE001 - report and carry on
            print(f"  !! {path.name}: {exc}", file=sys.stderr)

    lines = [
        "# Generated by tools/build_images.py - do not edit by hand.",
        "# Maps each original in assets/img to its WebP derivatives and to its",
        "# intrinsic size, so templates can set width/height and avoid reflow.",
        "",
    ]
    for e in entries:
        lines.append(f"{yaml_quote(e['key'])}:")
        lines.append(f"  slug: {yaml_quote(e['slug'])}")
        lines.append(f"  width: {e['width']}")
        lines.append(f"  height: {e['height']}")
        lines.append(f"  variants: [{', '.join(str(v) for v in e['variants'])}]")
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"images    : {len(entries)}")
    print(f"derivatives: {made} written, {skipped} already present")
    print(f"originals : {bytes_in / 1e6:.1f} MB")
    print(f"derived   : {bytes_out / 1e6:.1f} MB")
    print(f"manifest  : {MANIFEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
